name: Daily Commit Automation

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: "30 2 * * *"


jobs:
  commit-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Repository Activity - 22f2000526@ds.study.iitm.ac.in
        run: |
          echo "Last updated on $(date)" > last_update.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "22f2000526@ds.study.iitm.ac.in"
          git add last_update.txt
          git commit -m "Automated commit: $(date)"
          git push
